# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  server-test:
    name: Server → lint · build · test
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports: ["27017:27017"]
        options: >-
          --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Lint server
        working-directory: server
        run: npm run lint

      - name: Build server
        working-directory: server
        run: npm run build

      - name: Test server
        working-directory: server
        env:
          MONGODB_URI: mongodb://localhost:27017/tictactoe_test
        run: npm test

  client-test:
    name: Client → lint · build · test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Build client
        working-directory: client
        run: npm run build

      - name: Test client
        working-directory: client
        run: npm test
