name: Lint

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  server-lint:
    name: Server Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install server deps
        working-directory: server
        run: npm ci
      - name: Lint server
        working-directory: server
        run: npm run lint

  client-lint:
    name: Client Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install client deps
        working-directory: client
        run: npm ci
      - name: Lint client
        working-directory: client
        run: npm run lint
